CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(300) UNIQUE NOT NULL,
    login VARCHAR(300) UNIQUE NOT NULL,
    name VARCHAR(300) NOT NULL,
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS MPA_rating (
    MPA_id INT UNIQUE NOT NULL,
    MPA_name VARCHAR(30) NOT NULL,
    PRIMARY KEY (MPA_id)
    );

CREATE TABLE IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_rating_id INT REFERENCES MPA_rating(MPA_id) ON DELETE SET NULL
    );

CREATE TABLE IF NOT EXISTS friends (
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id INT REFERENCES users(user_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS genres (
    id INT UNIQUE NOT NULL,
    name VARCHAR(300) NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS films_genres (
    genres_id INT REFERENCES genres(id) ON DELETE CASCADE,
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genres_id)
    );

CREATE TABLE IF NOT EXISTS film_likes (
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );
